# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Spacehopper < Formula
  desc "Reboot annoying CLI programs with irritating failure modes."
  homepage "https://github.com/Emberwalker/spacehopper"
  version "0.0.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Emberwalker/spacehopper/releases/download/v0.0.3/spacehopper_0.0.3_darwin_amd64"
      sha256 "289e158dcf328072661ea131fcc0a9cac9d5894d7b9ff9ad8af2214fd6c37ef5"

      def install
        bin.install "spacehopper_0.0.3_darwin_amd64" => "spacehopper"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Emberwalker/spacehopper/releases/download/v0.0.3/spacehopper_0.0.3_darwin_arm64"
      sha256 "3aa2545b67f358e549113db825d07ef640ab48454eb841494e6145737576a4ec"

      def install
        bin.install "spacehopper_0.0.3_darwin_arm64" => "spacehopper"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Emberwalker/spacehopper/releases/download/v0.0.3/spacehopper_0.0.3_linux_amd64"
      sha256 "d444476a31a471855e6e55977b9ee34cf06ce7085799da9e17915577db526f0e"

      def install
        bin.install "spacehopper_0.0.3_linux_amd64" => "spacehopper"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Emberwalker/spacehopper/releases/download/v0.0.3/spacehopper_0.0.3_linux_arm64"
      sha256 "9ff12aa1a6598dbdd0a837b08fd7610628cfb35e9b12bcbd77035dad78d7d738"

      def install
        bin.install "spacehopper_0.0.3_linux_arm64" => "spacehopper"
      end
    end
  end

  test do
    system "#{bin}/program --version"
  end
end
