# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Spacehopper < Formula
  desc "Reboot annoying CLI programs with irritating failure modes."
  homepage "https://github.com/Emberwalker/spacehopper"
  version "0.0.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Emberwalker/spacehopper/releases/download/v0.0.2/spacehopper_0.0.2_darwin_amd64"
      sha256 "e4c082b02386f0b830e0c1ffd39ce39c9aaf5cc8846a838a7bf5ed5a3096a726"

      def install
        bin.install "spacehopper_0.0.2_darwin_amd64" => "spacehopper"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Emberwalker/spacehopper/releases/download/v0.0.2/spacehopper_0.0.2_darwin_arm64"
      sha256 "45f1d8f17619dd633d26b836bc47f67f064f832dd0af571e822d4d4ca6f98bff"

      def install
        bin.install "spacehopper_0.0.2_darwin_arm64" => "spacehopper"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Emberwalker/spacehopper/releases/download/v0.0.2/spacehopper_0.0.2_linux_amd64"
      sha256 "1930d223c958319cf19d7c2a8c60e799ac6c0e855474e5fe8ad94eb62ec9e2fb"

      def install
        bin.install "spacehopper_0.0.2_linux_amd64" => "spacehopper"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Emberwalker/spacehopper/releases/download/v0.0.2/spacehopper_0.0.2_linux_arm64"
      sha256 "42bd113efb71758c0c83d73f1a35249a0e4a4bb5161891aabb09515e4d1996c2"

      def install
        bin.install "spacehopper_0.0.2_linux_arm64" => "spacehopper"
      end
    end
  end

  test do
    system "#{bin}/program --version"
  end
end
